"""
PDF compatibility-report export (Section 5, module 8).

Generates a one-page PDF summarizing a vehicle lookup + risk prediction
result, visually preserving the Verified/Estimated/Prediction distinction.
"""

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


def generate_compatibility_pdf(
    vehicle_lookup: dict,
    risk_prediction: dict | None = None,
) -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    y = height - 25 * mm

    c.setFont("Helvetica-Bold", 18)
    c.drawString(20 * mm, y, "E20-Shield Compatibility Report")
    y -= 12 * mm

    match_type = vehicle_lookup.get("match_type", "estimated")
    badge_color = colors.HexColor("#22C55E") if match_type == "verified" else colors.HexColor("#F97316")
    c.setFillColor(badge_color)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(20 * mm, y, match_type.upper())
    c.setFillColor(colors.black)
    y -= 10 * mm

    c.setFont("Helvetica-Bold", 14)
    c.drawString(
        20 * mm, y,
        f"{vehicle_lookup.get('make')} {vehicle_lookup.get('model')} ({vehicle_lookup.get('mfg_year')})"
    )
    y -= 10 * mm

    c.setFont("Helvetica", 11)
    fields = [
        ("Emission standard", vehicle_lookup.get("emission_standard")),
        ("Max safe ethanol %", f"E{vehicle_lookup.get('max_safe_ethanol_pct')}"),
        ("Confidence", vehicle_lookup.get("confidence")),
    ]
    for label, value in fields:
        c.drawString(20 * mm, y, f"{label}: {value}")
        y -= 7 * mm

    source = vehicle_lookup.get("source_reference") or vehicle_lookup.get("disclaimer", "")
    y -= 3 * mm
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(20 * mm, y, source[:110])
    y -= 12 * mm

    if risk_prediction:
        c.setFont("Helvetica-Bold", 13)
        c.drawString(20 * mm, y, "Component Wear Risk (Model Prediction)")
        y -= 8 * mm
        c.setFont("Helvetica", 11)
        c.drawString(
            20 * mm, y,
            f"Health score: {risk_prediction.get('component_health_score')}/100 "
            f"(CI: {risk_prediction.get('confidence_interval_low')}-{risk_prediction.get('confidence_interval_high')})"
        )
        y -= 7 * mm
        c.drawString(
            20 * mm, y,
            f"Est. months to service need: {risk_prediction.get('estimated_months_to_service_need')}"
        )
        y -= 10 * mm
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(20 * mm, y, risk_prediction.get("disclaimer", "")[:110])
        y -= 10 * mm

    c.setFont("Helvetica", 8)
    c.setFillColor(colors.grey)
    c.drawString(20 * mm, 15 * mm, "Generated by E20-Shield — not a substitute for professional mechanical or legal advice.")

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer.read()
